// Optional real-browser smoke test. Pass a Playwright module path as argv[2].
const { chromium } = require(process.argv[2] || 'playwright');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
  try {
    const page=await browser.newPage({viewport:{width:1366,height:768}});
    const errors=[];page.on('pageerror',e=>errors.push(String(e)));
    page.on('console',m=>{if(m.type()==='error')console.log('browser error',m.text());});
    await page.goto('http://127.0.0.1:4317/');
    await page.locator('#settingsButton').click();
    await page.locator('#postureToggle').click();
    await page.locator('#blinkDetectionToggle').click();
    await page.locator('#closeFeatureDialog').click();
    await page.locator('#startButton').click();
    await page.waitForFunction(()=>!document.querySelector('#startButton').disabled,{},{timeout:65000});
    console.log('status', await page.locator('#cameraTitle').textContent());
    await page.waitForFunction(()=>getBlinkGuardianDiagnostics().posture.processedFrames>=2,{},{timeout:30000});
    console.log('diagnostics',await page.evaluate(()=>getBlinkGuardianDiagnostics()));
    console.log('layout',await page.locator('.monitor').boundingBox(),await page.locator('#startButton').boundingBox());
    const bounds=await page.locator('#startButton').boundingBox();
    assert.ok(bounds.y>=0 && bounds.y+bounds.height<=768,'Primary controls fit desktop viewport');
    const shot=async name=>{const path=join(tmpdir(),'blink-'+name+'.png');await page.screenshot({path});console.log('screenshot',path);};
    await shot('desktop');
    await page.locator('#settingsButton').click();
    const loaded=await page.locator('#postureBaseline').isEnabled();
    console.log('baseline enabled',loaded);
    await shot('settings');
    await page.locator('#closeFeatureDialog').click();
    if((await page.locator('#startButton').textContent())==='停止監測') await page.locator('#startButton').click();
    await page.locator('#settingsButton').click();
    await page.locator('#blinkDetectionToggle').click();
    await page.locator('#distanceDetectionToggle').click();
    await page.locator('#closeFeatureDialog').click();
    await page.locator('#startButton').click();
    await page.waitForFunction(()=>getBlinkGuardianDiagnostics().posture.processedFrames>=2 && getBlinkGuardianDiagnostics().inference.sampleCount>0,{},{timeout:65000});
    await page.locator('#settingsButton').click();
    await page.locator('#postureToggle').click();
    await page.waitForFunction(()=>!document.querySelector('#postureToggle').disabled);
    const count=await page.evaluate(()=>getBlinkGuardianDiagnostics().posture.processedFrames);
    await page.waitForFunction(()=>getBlinkGuardianDiagnostics().inference.sampleCount>=5);
    assert.equal(await page.evaluate(()=>getBlinkGuardianDiagnostics().posture.processedFrames),count,'Disabling posture stops its worker');
    await page.locator('#closeFeatureDialog').click();
    await page.locator('#startButton').click();
    assert.equal(await page.evaluate(()=>getBlinkGuardianDiagnostics().camera),null);
    console.log('combined models, live posture toggle and camera release passed');
    await page.setViewportSize({width:390,height:844});
    await page.reload();
    await shot('mobile');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
    await page.setViewportSize({width:320,height:240});
    await page.goto('http://127.0.0.1:4317/?mode=mini');
    await page.locator('#miniSettingsButton').click();
    console.log('mini dialog',await page.locator('#featureDialog').boundingBox());
    await shot('mini');
    console.log('errors',errors);
    assert.deepEqual(errors,[]);assert.equal(loaded,true,'Pose model must initialize in worker');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
